name:               "Shanshan"
description:        "Personal Blog"

url:                "Shanshan-IC.github.io"
author:             "Shanshan-IC"
email:              "33sharewithu@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "jhondoe"
email:              "33sharewithu@gmail.com"
github:             "Shanshan-IC"
pinterest:          "jhondoe"
linkedin:           "shanshan-fu-549230107"
facebook:           "fu.shanshan.33"
weibo:              "1005052079930097"
disqus_shortname:   "thinker3197"

background:         "img/home/me.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate